version: "3.8"
name: 'BookStore-microservices'
services:
  catalogue-service:
    image: victor140/bookstore-catalogue-service
    container_name: catalogue-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalogue-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalogue-db:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m